//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGCursosFormacionSergio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUMNOS
    {
        public int Id_Alumno { get; set; }
        public string Dni { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Email { get; set; }
        public Nullable<int> Curso { get; set; }
        public byte[] Foto { get; set; }
    
        public virtual CURSOS CURSOS { get; set; }
    }
}
