//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGCursosFormacionSergio
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURSOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CURSOS()
        {
            this.ALUMNOS = new HashSet<ALUMNOS>();
        }
    
        public int Id_Curso { get; set; }
        public string Nombre_Curso { get; set; }
        public int Horas { get; set; }
        public int Familia { get; set; }
        public int Estado { get; set; }
        public System.DateTime Fecha_Inicio { get; set; }
        public System.DateTime Fecha_Fin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALUMNOS> ALUMNOS { get; set; }
        public virtual ESTADOS ESTADOS { get; set; }
        public virtual FAMILIAS FAMILIAS { get; set; }
    }
}
